### ISSUE TITLE
Masculinity

### ISSUE THREAD

**Issue by simsevi** [hohmannr/xccp#1]
The crosshair seems like a very masculine element. What are you doing towards improving diversity?

**Comment by hohmannr** [comment]
The code provided is designed to be easily hackable. You can easily change the cursor font provided to one of your liking. Just change the `XC_crosshair` to any of the values described here: https://tronche.com/gui/x/xlib/appendix/b/.

You then can decide yourself how much masculinity your cursor needs. If there should be more, there is always `XC_man` or `XC_pirate`!
